name: CD

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Create release PR
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"What''s new"},{"type":"fix","section":"Fixes"}]'
          path: packages/itwinui-css

  publish:
    name: Publish npm package
    needs: release-please
    if: needs.release-please.outputs.release-created
    uses: ./.github/workflows/publish-npm.yml
    with:
      package: itwinui-css
      tag: latest
    secrets:
      NPMJS_PUBLISH_ITWIN: ${{ secrets.NPMJS_PUBLISH_ITWIN }}

  fix-title:
    name: Edit release title
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release-created

    steps:
      - name: Update release title to match tag name
        uses: actions/github-script@v4
        with:
          script: |
            const { data: release } = await github.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            if (release.name !== release.tag_name) {
              await github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
                name: release.tag_name
              });
            }
